### ISSUE TITLE
Handle directory changes

### ISSUE THREAD

**Issue by daceej** [waffle-ops/waffle#59]
Waffle currently assumes that commands are run from the current working directory. This can cause issues for example if you have your .waffle.yml file one directory above the docroot. Any release scripts / tasks relative to the docroot will break if you current directory is the root of the project.

**Comment by CoderBrandon** [comment]
An example of where this is causing problems:
```
tasks:
  cd-docroot: "cd docroot"
  release: "../scripts/releases/release.sh local"

recipes:
  release:
    - cd-docroot
    - release
```

When running `wfl recipe:release`, the directory changes from `cd-docroot` are not persisted when starting the `release` task.
